#include "pch.h"
#include "classInfo.h"

const std::vector<std::string> gClassNames = {
    "AcDbEntity",
    "AcDbBlockReference",
    "AcDbMInsertBlock",
    "AcDbTable",
    "AcDbViewRepBlockReference",
    "AcDbCamera",
    "AcDbFace",
    "AcDbFcf",
    "AcDbFrame",
    "AcDbOleFrame",
    "AcDbOle2Frame",
    "AcDbHatch",
    "AcDbImage",
    "AcDbRasterImage",
    "AcDbWipeout",
    "AcDbLight",
    "AcDbMLeader",
    "AcDbMline",
    "AcDbMPolygon",
    "AcDbMText",
    "AcDbPoint",
    "AcDbPolyFaceMesh",
    "AcDbPolygonMesh",
    "AcDbProxyEntity",
    "AcDbSection",
    "AcDbShape",
    "AcDbSolid",
    "AcDbText",
    "AcDbAttribute",
    "AcDbAttributeDefinition",
    "AcDbTrace",
    "AcDbViewport",
    "AcDbCurve",
    "AcDb2dPolyline",
    "AcDb3dPolyline",
    "AcDbArc",
    "AcDbCircle",
    "AcDbEllipse",
    "AcDbLeader",
    "AcDbLine",
    "AcDbPolyline",
    "AcDbRay",
    "AcDbSpline",
    "AcDbHelix",
    "AcDbXline",
    "AcDbDimension",
    "AcDb2LineAngularDimension",
    "AcDb3PointAngularDimension",
    "AcDbAlignedDimension",
    "AcDbArcDimension",
    "AcDbDiametricDimension",
    "AcDbOrdinateDimension",
    "AcDbRadialDimension",
    "AcDbRadialDimensionLarge",
    "AcDbRotatedDimension",
    "AcDb3dSolid",
    "AcDbBody",
    "AcDbRegion",
    "AcDbSubDMesh",
    // "AcDbBlockBegin",
    // "AcDbBlockEnd",
    // "AcDbSequenceEnd",
    "AcDbSurface",
    "AcDbExtrudedSurface",
    "AcDbLoftedSurface",
    "AcDbNurbSurface",
    "AcDbPlaneSurface",
    "AcDbRevolvedSurface",
    "AcDbSweptSurface",
    // "AcDbVertex",
    // "AcDb2dVertex",
    // "AcDb3dPolylineVertex",
    // "AcDbFaceRecord",
    // "AcDbPolyFaceMeshVertex",
    // "AcDbPolygonMeshVertex",
    "AcDbViewBorder",
    "AcDbViewSymbol",
    "AcDbDetailSymbol",
    "AcDbSectionSymbol",
    "AcDbUnderlayReference",
    "AcDbDgnReference",
    "AcDbDwfReference",
    "AcDbPdfReference"
};

const std::map<std::string, std::vector<std::string>> gSubclassMap = {
    {"AcDbEntity", {"AcDbBlockReference", "AcDbCamera", "AcDbFace", "AcDbFcf", "AcDbFrame",
                    "AcDbHatch", "AcDbImage", "AcDbLight", "AcDbMLeader", "AcDbMline", "AcDbMPolygon",
                    "AcDbMText", "AcDbPoint", "AcDbPolyFaceMesh", "AcDbPolygonMesh", "AcDbProxyEntity",
                    "AcDbSection", "AcDbShape", "AcDbSolid", "AcDbText", "AcDbTrace", "AcDbViewport",
                    "AcDbCurve", "AcDbDimension", "AcDb3dSolid", "AcDbBody", "AcDbRegion",
                    "AcDbSubDMesh", /* "AcDbBlockBegin", "AcDbBlockEnd", "AcDbSequenceEnd", */
                    "AcDbSurface", /* "AcDbVertex", */ "AcDbViewBorder", "AcDbViewSymbol",
                    "AcDbUnderlayReference"}},
    {"AcDbBlockReference", {"AcDbMInsertBlock", "AcDbTable", "AcDbViewRepBlockReference"}},
    {"AcDbFrame", {"AcDbOleFrame"}},
    {"AcDbOleFrame", {"AcDbOle2Frame"}},
    {"AcDbImage", {"AcDbRasterImage"}},
    {"AcDbRasterImage", {"AcDbWipeout"}},
    {"AcDbText", {"AcDbAttribute", "acDbAttributeDefinition"}},
    {"AcDbCurve", {"AcDb2dPolyline", "AcDb3dPolyline", "AcDbArc", "AcDbCircle", "AcDbEllipse",
                   "AcDbLeader", "AcDbLine", "AcDbPolyline", "AcDbRay", "AcDbSpline", "AcDbXline"}},
    {"AcDbSpline", {"AcDbHelix"}},
    {"AcDbDimension", {"AcDb2LineAngularDimension", "AcDb3PointAngularDimension", "AcDbAlignedDimension",
                       "AcDbArcDimension", "AcDbDiametricDimension", "AcDbOrdinateDimension",
                       "AcDbRadialDimension", "AcDbRadialDimensionLarge", "AcDbRotatedDimension"}},
    {"AcDbSurface", {"AcDbExtrudedSurface", "AcDbLoftedSurface", "AcDbNurbSurface", "AcDbPlaneSurface",
                     "AcDbRevolvedSurface", "AcDbSweptSurface"}},
                     /* {"AcDbVertex", {"AcDb2dVertex", "AcDb3dPolylineVertex", "AcDbFaceRecord", "AcDbPolyFaceMeshVertex",
                                         "AcDbPolygonMeshVertex"}}, */
                     {"AcDbViewSymbol", {"AcDbDetailSymbol", "AcDbSectionSymbol"}},
                     {"AcDbUnderlayReference", {"AcDbDgnReference", "AcDbDwfReference", "AcDbPdfReference"}}
};